version: '3'

services:
  proxy:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
  frontend:
    container_name: frontend
    image: robertnichita/gwiz:frontend
    volumes:
      - ./frontend/:/src/usr/frontend/
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context : ./frontend
    ports:
     - "3000:3000"
  backend:
    container_name: backend
    image: robertnichita/gwiz:backend
    volumes:
      - ./backend/:/src/usr/backend/
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context : ./backend
    ports:
     - "5000:5000"