version: '3'

services:
  proxy:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    depends_on:
      - backend
      - frontend
  frontend:
    container_name: frontend
    image: robertnichita/gwiz:frontend
    volumes:
      - ./frontend/:/src/usr/frontend/
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context : ./frontend
      args:
        environment: development
    ports:
     - "3000:3000"
  backend:
    container_name: backend
    image: robertnichita/gwiz:backend
    volumes:
      - ./backend/:/src/usr/backend/
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mongo
      - QUEUE_URL=amqp://rabbitmq:5672
    build:
      dockerfile: Dockerfile
      context : ./backend
      args:
        environment : development
    ports:
     - "4000:4000"