version: '3'

services:
  proxy:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/
    ports:
     - "80"
  frontend:
    container_name: frontend
    image: robertnichita/gwiz:frontend
    ports:
     - "3000"
  backend:
    container_name: backend
    image: robertnichita/gwiz:backend
    ports:
     - "5000"