version: "3"
services:
  # Credentials: guest;guest
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq # Needed, see docs: https://hub.docker.com/_/rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672 # AMQP
        - 15672:15672 # Management UI
  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile
    environment:
      - QUEUE_AMQP_URL=amqp://rabbitmq:5672
      - AWS_ACCESS_KEY_ID=secret
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_REGION=us-east-1
    volumes:
      - ./:/worker
    depends_on:
      - rabbitmq
    restart: always